// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqodumozuksstzczpybl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxb2R1bW96dWtzc3R6Y3pweWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjg1ODAsImV4cCI6MjA3MTIwNDU4MH0.Te_DNvfF5pb5FC6S-du309Y9UawoNnXXRGaWffIjpTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});