// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wroxtrwpisnqmxqcdfij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indyb3h0cndwaXNucW14cWNkZmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTI0NzUsImV4cCI6MjA2ODk4ODQ3NX0.jamA--a03rbiPQ9J6SniHBU8_wi0IYTMSyIMqGtvy2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});